import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#005236',
        'primary-fixed': '#dce1ff',
        'on-primary-container': '#90a8ff',
        'on-surface': '#0b1c30',
        'outline-variant': '#c5c5d3',
        'primary': '#00236f',
        'on-tertiary-container': '#ef9900',
        'tertiary-fixed-dim': '#ffb95f',
        'surface-tint': '#4059aa',
        'inverse-on-surface': '#eaf1ff',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        'surface-container-highest': '#d3e4fe',
        'surface-container-high': '#dce9ff',
        'surface-bright': '#f8f9ff',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#ffddb8',
        'on-secondary': '#ffffff',
        'inverse-primary': '#b6c4ff',
        'secondary-container': '#6cf8bb',
        'background': '#f8f9ff',
        'surface-container': '#e5eeff',
        'secondary': '#006c49',
        'secondary-fixed': '#6ffbbe',
        'surface': '#f8f9ff',
        'tertiary': '#3e2400',
        'on-secondary-container': '#00714d',
        'surface-dim': '#cbdbf5',
        'inverse-surface': '#213145',
        'error': '#ba1a1a',
        'primary-container': '#1e3a8a',
        'outline': '#757682',
        'surface-variant': '#d3e4fe',
        'on-background': '#0b1c30',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#b6c4ff',
        'on-primary-fixed': '#00164e',
        'surface-container-low': '#eff4ff',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5c3800',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#264191',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#4edea3',
        'on-error': '#ffffff',
        'on-surface-variant': '#444651',
        'on-secondary-fixed': '#002113',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        'sm': '8px',
        'base': '4px',
        'gutter': '24px',
        'xl': '32px',
        'sidebar-width': '260px',
        'lg': '24px',
        'xs': '4px',
        'md': '16px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      animation: {
        'typing': 'typing 1.4s infinite',
        'pulse-subtle': 'pulse-subtle 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fade-in 0.3s ease-out',
        'count-up': 'count-up 1.5s ease-out',
      },
      keyframes: {
        typing: {
          '0%, 60%, 100%': { transform: 'translateY(0)' },
          '30%': { transform: 'translateY(-4px)' },
        },
        'pulse-subtle': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.85' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}

export default config
